-- AlterTable
ALTER TABLE "Flight" ADD COLUMN     "destLat" DOUBLE PRECISION,
ADD COLUMN     "destLon" DOUBLE PRECISION,
ADD COLUMN     "originLat" DOUBLE PRECISION,
ADD COLUMN     "originLon" DOUBLE PRECISION;
